
START TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ WRITE;

CREATE SCHEMA ORMModel1 DEFAULT CHARACTER SET UTF8;

SET SCHEMA 'ORMMODEL1';

CREATE TABLE ORMModel1."User"
(
	userId INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	name CHARACTER(50),
	phone CHARACTER(50),
	CONSTRAINT User_PK PRIMARY KEY(userId)
);

COMMIT WORK;
