//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace myPword {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class WebSites : DataSet {
        
        private sitenameDataTable tablesitename;
        
        public WebSites() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected WebSites(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["sitename"] != null)) {
                    this.Tables.Add(new sitenameDataTable(ds.Tables["sitename"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public sitenameDataTable sitename {
            get {
                return this.tablesitename;
            }
        }
        
        public override DataSet Clone() {
            WebSites cln = ((WebSites)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["sitename"] != null)) {
                this.Tables.Add(new sitenameDataTable(ds.Tables["sitename"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tablesitename = ((sitenameDataTable)(this.Tables["sitename"]));
            if ((this.tablesitename != null)) {
                this.tablesitename.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "WebSites";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/Data.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = false;
            this.tablesitename = new sitenameDataTable();
            this.Tables.Add(this.tablesitename);
        }
        
        private bool ShouldSerializesitename() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void sitenameRowChangeEventHandler(object sender, sitenameRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class sitenameDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnid;
            
            private DataColumn columnvalue;
            
            private DataColumn columnun;
            
            private DataColumn columnpw;
            
            internal sitenameDataTable() : 
                    base("sitename") {
                this.InitClass();
            }
            
            internal sitenameDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn idColumn {
                get {
                    return this.columnid;
                }
            }
            
            internal DataColumn valueColumn {
                get {
                    return this.columnvalue;
                }
            }
            
            internal DataColumn unColumn {
                get {
                    return this.columnun;
                }
            }
            
            internal DataColumn pwColumn {
                get {
                    return this.columnpw;
                }
            }
            
            public sitenameRow this[int index] {
                get {
                    return ((sitenameRow)(this.Rows[index]));
                }
            }
            
            public event sitenameRowChangeEventHandler sitenameRowChanged;
            
            public event sitenameRowChangeEventHandler sitenameRowChanging;
            
            public event sitenameRowChangeEventHandler sitenameRowDeleted;
            
            public event sitenameRowChangeEventHandler sitenameRowDeleting;
            
            public void AddsitenameRow(sitenameRow row) {
                this.Rows.Add(row);
            }
            
            public sitenameRow AddsitenameRow(string id, string value, string un, string pw) {
                sitenameRow rowsitenameRow = ((sitenameRow)(this.NewRow()));
                rowsitenameRow.ItemArray = new object[] {
                        id,
                        value,
                        un,
                        pw};
                this.Rows.Add(rowsitenameRow);
                return rowsitenameRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                sitenameDataTable cln = ((sitenameDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new sitenameDataTable();
            }
            
            internal void InitVars() {
                this.columnid = this.Columns["id"];
                this.columnvalue = this.Columns["value"];
                this.columnun = this.Columns["un"];
                this.columnpw = this.Columns["pw"];
            }
            
            private void InitClass() {
                this.columnid = new DataColumn("id", typeof(string), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnid);
                this.columnvalue = new DataColumn("value", typeof(string), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnvalue);
                this.columnun = new DataColumn("un", typeof(string), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnun);
                this.columnpw = new DataColumn("pw", typeof(string), null, System.Data.MappingType.Attribute);
                this.Columns.Add(this.columnpw);
                this.columnid.Namespace = "";
                this.columnvalue.Namespace = "";
                this.columnun.Namespace = "";
                this.columnpw.Namespace = "";
            }
            
            public sitenameRow NewsitenameRow() {
                return ((sitenameRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new sitenameRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(sitenameRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.sitenameRowChanged != null)) {
                    this.sitenameRowChanged(this, new sitenameRowChangeEvent(((sitenameRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.sitenameRowChanging != null)) {
                    this.sitenameRowChanging(this, new sitenameRowChangeEvent(((sitenameRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.sitenameRowDeleted != null)) {
                    this.sitenameRowDeleted(this, new sitenameRowChangeEvent(((sitenameRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.sitenameRowDeleting != null)) {
                    this.sitenameRowDeleting(this, new sitenameRowChangeEvent(((sitenameRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovesitenameRow(sitenameRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class sitenameRow : DataRow {
            
            private sitenameDataTable tablesitename;
            
            internal sitenameRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tablesitename = ((sitenameDataTable)(this.Table));
            }
            
            public string id {
                get {
                    try {
                        return ((string)(this[this.tablesitename.idColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesitename.idColumn] = value;
                }
            }
            
            public string value {
                get {
                    try {
                        return ((string)(this[this.tablesitename.valueColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesitename.valueColumn] = value;
                }
            }
            
            public string un {
                get {
                    try {
                        return ((string)(this[this.tablesitename.unColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesitename.unColumn] = value;
                }
            }
            
            public string pw {
                get {
                    try {
                        return ((string)(this[this.tablesitename.pwColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesitename.pwColumn] = value;
                }
            }
            
            public bool IsidNull() {
                return this.IsNull(this.tablesitename.idColumn);
            }
            
            public void SetidNull() {
                this[this.tablesitename.idColumn] = System.Convert.DBNull;
            }
            
            public bool IsvalueNull() {
                return this.IsNull(this.tablesitename.valueColumn);
            }
            
            public void SetvalueNull() {
                this[this.tablesitename.valueColumn] = System.Convert.DBNull;
            }
            
            public bool IsunNull() {
                return this.IsNull(this.tablesitename.unColumn);
            }
            
            public void SetunNull() {
                this[this.tablesitename.unColumn] = System.Convert.DBNull;
            }
            
            public bool IspwNull() {
                return this.IsNull(this.tablesitename.pwColumn);
            }
            
            public void SetpwNull() {
                this[this.tablesitename.pwColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class sitenameRowChangeEvent : EventArgs {
            
            private sitenameRow eventRow;
            
            private DataRowAction eventAction;
            
            public sitenameRowChangeEvent(sitenameRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public sitenameRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
