//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pWordLib {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class pWordSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static pWordSettings defaultInstance = ((pWordSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new pWordSettings())));
        
        public static pWordSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0_0_6B")]
        public string version {
            get {
                return ((string)(this["version"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TreeBackground {
            get {
                return ((global::System.Drawing.Color)(this["TreeBackground"]));
            }
            set {
                this["TreeBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120, 70, 50")]
        public global::System.Drawing.Color SelectedNodeBackground {
            get {
                return ((global::System.Drawing.Color)(this["SelectedNodeBackground"]));
            }
            set {
                this["SelectedNodeBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beige")]
        public global::System.Drawing.Color SelectedNodeForeground {
            get {
                return ((global::System.Drawing.Color)(this["SelectedNodeForeground"]));
            }
            set {
                this["SelectedNodeForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TreeviewBackground {
            get {
                return ((global::System.Drawing.Color)(this["TreeviewBackground"]));
            }
            set {
                this["TreeviewBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TreeviewForeground {
            get {
                return ((global::System.Drawing.Color)(this["TreeviewForeground"]));
            }
            set {
                this["TreeviewForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 192")]
        public global::System.Drawing.Color ValueTextViewer {
            get {
                return ((global::System.Drawing.Color)(this["ValueTextViewer"]));
            }
            set {
                this["ValueTextViewer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TreeViewLinesVisible {
            get {
                return ((bool)(this["TreeViewLinesVisible"]));
            }
            set {
                this["TreeViewLinesVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPrefix {
            get {
                return ((bool)(this["ShowPrefix"]));
            }
            set {
                this["ShowPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSuffix {
            get {
                return ((bool)(this["ShowSuffix"]));
            }
            set {
                this["ShowSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RabitHolePrefix {
            get {
                return ((bool)(this["RabitHolePrefix"]));
            }
            set {
                this["RabitHolePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RabitHoleSuffix {
            get {
                return ((bool)(this["RabitHoleSuffix"]));
            }
            set {
                this["RabitHoleSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAttributes {
            get {
                return ((bool)(this["ShowAttributes"]));
            }
            set {
                this["ShowAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowNamespace {
            get {
                return ((bool)(this["ShowNamespace"]));
            }
            set {
                this["ShowNamespace"] = value;
            }
        }
    }
}
